version: '3.8'

services:
  auth_service:
    build:
      context: ../auth_service
      dockerfile: ../docker/Dockerfile.auth
    user: "${UID}:${GID}"
    volumes:
      - ../auth_service:/app
    container_name: auth_service
    env_file:
      - ../envs/.env_auth
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    stdin_open: true
    tty: true
    networks:
      - app_network
    # depends_on:
    #   - db

  profile_service:
    build:
      context: ../profile_service
      dockerfile: ../docker/Dockerfile.profile
    user: "${UID}:${GID}"
    volumes:
      - ../profile_service:/app
    container_name: profile_service
    env_file:
      - ../envs/.env_profile
    ports:
      - "8001:8001"
      # - "8001:8000"
    environment:
      - PYTHONUNBUFFERED=1
    stdin_open: true
    tty: true
    networks:
      - app_network
    # depends_on:
    #   - db

  trade_service:
    build:
      context: ../trade_service
      dockerfile: ../docker/Dockerfile.trade
    user: "${UID}:${GID}"
    volumes:
      - ../trade_service:/app
    container_name: trade_service
    env_file:
      - ../envs/.env_trade
    ports:
      - "8002:8002"
      # - "8002:8000"
    environment:
      - PYTHONUNBUFFERED=1
    stdin_open: true
    tty: true
    networks:
      - app_network
    # depends_on:
    #   - db

  home_service:
    build:
      context: ../home_service
      dockerfile: ../docker/Dockerfile.home
    user: "${UID}:${GID}"
    volumes:
      - ../home_service:/app
    container_name: home_service
    env_file:
      - ../envs/.env_home
    ports:
      - "8003:8003"
      # - "8003:8000"
    environment:
      - PYTHONUNBUFFERED=1
    stdin_open: true
    tty: true
    networks:
      - app_network
    # depends_on:
    #   - db

  api_gateway:
    build:
      context: ../api_gateway
      dockerfile: ../docker/Dockerfile.gateway
    user: "${UID}:${GID}"
    volumes:
      - ../api_gateway:/app
    container_name: api_gateway
    env_file:
      - ../envs/.env_gateway
    ports:
      - "8004:8004"
    environment:
      - PYTHONUNBUFFERED=1
    stdin_open: true
    tty: true
    networks:
      - app_network

  # db:
  #   image: postgres:13
  #   container_name: postgres_db
  #   env_file:
  #     - ../envs/.env_db
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:

