version: '3'

services:
  django:
    build:
      context: .
    volumes:
      - .:/app  # Mapeia os arquivos locais para dentro do container
    ports:
      - "8000:8000"  # Mapeia a porta 8000 do container para a máquina local
    environment:
      - PYTHONUNBUFFERED=1
    stdin_open: true
    tty: true